/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnvDebugRouteImport } from './routes/env-debug'
import { Route as IndexRouteImport } from './routes/index'

const EnvDebugRoute = EnvDebugRouteImport.update({
  id: '/env-debug',
  path: '/env-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/env-debug': typeof EnvDebugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/env-debug': typeof EnvDebugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/env-debug': typeof EnvDebugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/env-debug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/env-debug'
  id: '__root__' | '/' | '/env-debug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvDebugRoute: typeof EnvDebugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/env-debug': {
      id: '/env-debug'
      path: '/env-debug'
      fullPath: '/env-debug'
      preLoaderRoute: typeof EnvDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvDebugRoute: EnvDebugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
